project:
  type: website
  render:
    - "!code/*"
    - slides/
    - about.qmd
    - index.qmd
    - README.qmd
  output-dir: docs
  preview:
    port: 4200
    navigate: false
  post-render:
    - after-render.R
  #   - build-course-files.R

execute:
  freeze: auto  # re-render only when source changes
  error: true
  cache: false

website:
  title: "SISBID Data Visualization"

  repo-url: https://github.com/dicook/sisbid
  repo-actions: [issue]

  navbar:
    left:
      - href: index.html
        text: Home
        aria-label: Home
      - text: Day 1
        aria-label: Day 1 content
        menu:
          - href: slides/00-preamble.rjs.html
            text: Preamble
          - href: slides/01-ggplot.rjs.html
            text: 1. Data Visualizations
          - href: slides/02-perception.rjs.html
            text: 2. Perception
          - href: slides/03-tidyr.rjs.html
            text: 3. Tidying Data
          - href: slides/04-messy-it-up.rjs.html
            text: 4. Data Summaries
          - href: slides/05-wrangling.rjs.html
            text: 5. Wrangling
          - href: slides/06-ggplot-adv.rjs.html
            text: 6. Advancing ggplot
      - text: Day 2
        aria-label: Day 2 content
        menu:
          - href: slides/07-interactive-plots.rjs.html
            text: 7. Interactive plots
          - href: slides/08-shiny-apps.rjs.html
            text: 8. Shiny apps
          - href: slides/09-shiny-reactivity.rjs.html
            text: 9. Shiny reactivity
          - href: slides/10-mvplot.rjs.html
            text: 10. Multivariate Plots
          - href: slides/11-mvplot-tour.rjs.html
            text: 11. Tours
          - href: slides/12-adv-graphics.rjs.html
            text: 12. Advanced Graphics

      - text: Day 3
        aria-label: Day 3 content
        menu:
          - href: slides/13-theme-shiny.rjs.html
            text: 13. Theming Shiny
          - href: slides/14-build-shiny-app.rjs.html
            text: 14. Polishing a Shiny App
          - href: slides/15-interactive-document.rjs.html
            text: 15. Interactive Documents

format:
  html:
    theme:
      light: ['css/my-light.scss', 'css/custom.scss', flatly]
      dark: ['css/my-dark.scss', 'css/custom.scss', darkly]
    respect-user-color-scheme: true
    toc: true


