## ----echo = FALSE, message = FALSE, warning = FALSE, warning = FALSE----------
# source(here("knitr-setup.R"))
# source(here("libraries.R"))

library(ggplot2)
library(vinference)
library(nullabor)
library(readr)
library(dplyr)
library(tidyr)
library(forecast)
library(stringr)
library(here)
library(readxl)
library(purrr)
library(fiftystater)
theme_set(theme_bw())


## ----eval = F-----------------------------------------------------------------
# ggplot(data) + geom_point(aes(x=x1, y=x2))            #  A
# ggplot(data) + geom_point(aes(x=x1, y=x2, colour=cl)) #  B
# ggplot(data) + geom_histogram(aes(x=x1))              #  C
# ggplot(data) + geom_boxplot(aes(x=cl, y=x1))          #  D


## ----lineup 1, fig.height=6, fig.width=6, echo=T------------------------------
#| output-location: "column"
# Make a lineup of mtcars data
# 20 plots, one data, 19 nulls
# Which one is different?
set.seed(20190709)
library(ggplot2)
ggplot(
  lineup(
    null_permute('mpg'), 
    mtcars), 
  aes(mpg, wt)
) +
  geom_point() +
  facet_wrap(~ .sample)


## ----embed the data plot in a field of null plots, eval = F-------------------
# pos <- sample(1:20, 1)
# df_null <- lineup(
#   null_permute('v1'),
#   df, pos=pos)
# ggplot(
#   df_null,
#   aes(x=v2, y=v1, fill=v2)
# ) +
#   geom_boxplot() +
#   facet_wrap(~.sample, ncol=5) +
#   coord_flip()


## ----penguins-lineup-ex, echo = F, message = F, warning = F-------------------
set.seed(203482093)
data(penguins)
pos <- sample(1:20, 1)
df_null <- lineup(null_permute('bill_len'), penguins, pos=pos)
ggplot(df_null, aes(x=bill_dep, y=bill_len, fill=species)) + 
  geom_boxplot() +
  facet_wrap(~.sample, ncol=5) + coord_flip() + 
  guides(fill = 'none') +
  theme(axis.text = element_blank(), axis.title = element_blank(), axis.ticks = element_blank())


## ----compute pvalue-----------------------------------------------------------
library(nullabor)
pvisual(4, 17, m=20)


## ----adjusted for variability in the plots------------------------------------
library(vinference)
c("alpha = 0.01" = pVis(4,17,m=20, alpha=0.01, lower.tail=FALSE),
  "alpha = 0.15" = pVis(4,17,m=20, alpha=0.15, lower.tail=FALSE),
  "alpha = 1" = pVis(4,17,m=20, alpha=1, lower.tail=FALSE))


## ----lineup 2, fig.height=6, message = F, warning = F, eval=F-----------------
# # Assessing model fit, using a lineup of residual plots: 19 nulls + 1 resid plot
# # Structure in the residual plot corresponding to less than random variation?
# # Nulls are generated by `rotating` residuals after model fit.
# tips <- read_csv("http://www.ggobi.org/book/data/tips.csv")
# x <- lm(tip ~ totbill, data = tips)
# tips.reg <- data.frame(tips, .resid = residuals(x), .fitted = fitted(x))
# ggplot(lineup(null_lm(tip ~ totbill, method = 'rotate'), tips.reg)) +
#   geom_point(aes(x = totbill, y = .resid)) +
#   facet_wrap(~ .sample)


## ----lineup 2, fig.height=6, message = F, warning = F, echo= F----------------
# Assessing model fit, using a lineup of residual plots: 19 nulls + 1 resid plot
# Structure in the residual plot corresponding to less than random variation?
# Nulls are generated by `rotating` residuals after model fit.
tips <- read_csv("http://www.ggobi.org/book/data/tips.csv")
x <- lm(tip ~ totbill, data = tips)
tips.reg <- data.frame(tips, .resid = residuals(x), .fitted = fitted(x))
ggplot(lineup(null_lm(tip ~ totbill, method = 'rotate'), tips.reg)) +
  geom_point(aes(x = totbill, y = .resid)) +
  facet_wrap(~ .sample)


## ----lineup 3, fig.height=6---------------------------------------------------
# Assessing time series model fit 
# Use simulation to produce null plots.
# Auto arima model used to match 
# the dependence structure in the data.
data(aud)
l <- lineup(null_ts("rate", auto.arima), aud)


## ----echo=T-------------------------------------------------------------------
#| output-location: "column"
ggplot(l, aes(x=date, y=rate)) + 
  geom_line() +
  facet_wrap(~.sample, 
             scales="free_y") +
  theme(axis.text = 
          element_blank()) +
  xlab("") + ylab("")


## ----lets talk TB, echo=FALSE,  message = F, warning = F----------------------
tb <- read_csv(here("data/TB_notifications_2020-07-01.csv")) |> 
  select(country, iso3, year, new_sp_m04:new_sp_fu) |>
  pivot_longer(cols=new_sp_m04:new_sp_fu, names_to="sexage", values_to="count") |>
  mutate(sexage = str_replace(sexage, "new_sp_", "")) |>
  mutate(sex=substr(sexage, 1, 1), 
         age=substr(sexage, 2, length(sexage))) |>
  select(-sexage)

# Filter years between 1997 and 2012 due to missings
tb_us <- tb |> 
  filter(country == "United States of America") |>
  filter(!(age %in% c("04", "014", "514", "u"))) |>
  filter(year > 1996, year < 2013)


## ----fig.width=10, fig.height=3,echo=F----------------------------------------
ggplot(tb_us, aes(x = year, y = count, fill = sex)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_grid(~ age) +
  scale_fill_brewer(palette="Dark2")


## ----generate a lineup of three binomial simulations, echo=TRUE---------------
# Make expanded rows of categorical variables matching the 
# counts of aggregated data. Sex needs to be converted to 0, 1
# to match binomial output.
tb_us_long <- uncount(tb_us, count)
tb_us_long <- tb_us_long |>
  mutate(sex01 = ifelse(sex=="m", 0, 1)) |>
  select(-sex)

# Generate a lineup of n=3, randomly choose the data position.
# Compute counts again.
pos = sample(1:3, 1)
l <- lineup(null_dist(var="sex01", dist="binom", 
                      list(size=1, p=0.5)), 
            true=tb_us_long, n=3, pos=pos)
l <- l |>
  group_by(.sample, year, age) |>
  count(sex01)


## ----tb-lineup-1, eval = F, echo=T--------------------------------------------
# ggplot(l, aes(x = year, y = n, fill = factor(sex01))) +
#   geom_bar(stat = "identity", position = "fill") +
#   facet_grid(.sample ~ age) +
#   scale_fill_brewer(palette="Dark2") +
#   theme(legend.position="none")


## ----tb-lineup-1, fig.height=6, fig.width=10, echo = F------------------------
ggplot(l, aes(x = year, y = n, fill = factor(sex01))) +
  geom_bar(stat = "identity", position = "fill") +
  facet_grid(.sample ~ age) +
  scale_fill_brewer(palette="Dark2") + 
  theme(legend.position="none")


## ----a more complicated null, echo=TRUE, code_copy=F--------------------------
tbl <- tb_us |> group_by(sex) |> summarise(count=sum(count)) # <1>
tbl # <1>
p <- tbl$count[1]/sum(tbl$count) # <1>

pos = sample(1:3, 1) # <2>
l <- lineup(null_dist(var="sex01", dist="binom",  # <2>
                      list(size=1, p=p)),  # <2>
            true=tb_us_long, n=3, pos=pos) # <2>
l <- l |> # <3>
  group_by(.sample, year, age) |>  # <3>
  count(sex01)  # <3>


## ----tb-lineup-2, eval = F, echo = T------------------------------------------
# ggplot(l, aes(x = year, y = n, fill = factor(sex01))) +
#   geom_bar(stat = "identity", position = "fill") +
#   facet_grid(.sample ~ age) +
#   scale_fill_brewer(palette="Dark2") +
#   theme(legend.position="none")


## ----tb-lineup-2, fig.height=6, fig.width=10, echo = F------------------------
ggplot(l, aes(x = year, y = n, fill = factor(sex01))) +
  geom_bar(stat = "identity", position = "fill") +
  facet_grid(.sample ~ age) +
  scale_fill_brewer(palette="Dark2") + 
  theme(legend.position="none")


## ----make a map lineup, fig.height=6, fig.width=16, fig.cap = "Cancer incidence across the US 2010-2014, Melanoma cases per 100k. [Data source: American Cancer Society](https://cancerstatisticscenter.cancer.org)."----
# Read xlsx spreadsheet on cancer incidence in USA, for a more
# complex lneup example, a lineup of maps
incd <- read_xlsx(here("data/IncRate.xlsx"), skip=6, sheet=2) |>
  filter(!(State %in% c("All U.S. combined", "Kansas"))) |>
  select(State, `Melanoma of the skin / Both sexes combined`) |>
  rename(Incidence=`Melanoma of the skin / Both sexes combined`) |>
  mutate(Incidence = as.numeric(substr(Incidence, 1, 3)))

# State names need to coincide between data sets
incd <- incd |> mutate(State = tolower(State))

# Choose a position 
pos <- 6

# Make lineup of cancer incidence
incd_lineup <- lineup(null_permute('Incidence'), incd, n=18, pos=pos)

# Join cancer incidence data to map polygons
incd_map <- left_join(fifty_states, filter(incd_lineup, .sample==1),
                      by=c("id"="State"))
for (i in 2:18) {
  x <- left_join(fifty_states, filter(incd_lineup, .sample==i),
                      by=c("id"="State"))
  incd_map <- bind_rows(incd_map, x)
}
# Remove Kansas - it was missing the cancer data
incd_map <- incd_map |> filter(!is.na(.sample))

# Plot the maps as a lineup
ggplot(incd_map) + 
  geom_polygon(aes(x=long, y=lat, fill = Incidence, group=group)) + 
  expand_limits(x = incd_map$long, y = incd_map$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  scale_fill_viridis_b(option = "D") + 
  theme(legend.position = "none", 
        panel.background = element_blank()) +
  facet_wrap(~.sample, ncol=6)


## ----eval=FALSE,echo=TRUE-----------------------------------------------------
# data(wasps)
# lda_pred <- function(x) {
#   d <- predict(lda(Group~.,
#                    data=x[,-43]))$x[,1:2] |>
#   as_tibble() |>
#   mutate(Group = x$Group)
#   return(d)
# }
# wasps_lineup <- lineup(null_permute('Group'),
#                        wasps[,-1], n=12) |>
#   as_tibble()
# wasps_lineup_lda <- wasps_lineup |>
#   split(.$.sample) |>
#   map_df(~lda_pred(.)) |>
#   mutate(.sample = wasps_lineup$.sample)
# ggplot(wasps_lineup_lda, aes(x=LD1, y=LD2,
#                              colour=Group)) +
#   geom_point() +
#   facet_wrap(~.sample, ncol=4) +
#   scale_colour_brewer(palette="Dark2") +
#   theme(legend.position="none")

