---
title: "TB Incidence Around the Globe"
author: "Di Cook"
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

## Data description

This is current tuberculosis data taken from [WHO](http://www.who.int/tb/country/data/download/en/), 
the case notifications table. The data looks like this:

```{r message=FALSE, echo=FALSE, warning=FALSE, error=FALSE}
library(tidyverse)
library(DT)
tb <- read_csv(here::here("data/TB_burden_countries_2025-07-22.csv")) |> 
  select(country, iso3, year, e_inc_100k) 

datatable(tb)
```

## Incidence

```{r message=FALSE, echo=FALSE, warning=FALSE, error=FALSE}
library(plotly)
p <- tb |> 
  filter(iso3 %in% c("AUS", "USA", "CAN", "KEN", "IND", "COL", "ASM")) |>
  ggplot() +
    geom_point(aes(x=iso3, y=e_inc_100k, frame=year))
ggplotly(p)
```

## Test your knowledge

```{r quiz1, message=FALSE, echo=FALSE, warning=FALSE, error=FALSE}
quiz(
  question("In which country does TB incidence per 100k change the most?",
    answer("   Australia"),
    answer("   USA"),
    answer("   Canada"),
    answer("   Indonesia"),
    answer("   Colombia"),
    answer("   Kenya", correct = TRUE),
    answer("   American Samoa")
  )
)
```
