on:
  workflow_dispatch:
  push:
    branches: master

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y \
          libcurl4-openssl-dev \
          libmpfr-dev \
          libabsl-dev \
          libgdal-dev \
          libglpk-dev \
          libgmp3-dev \
          libudunits2-dev


      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false

      - name: Quarto version
        run: |
          quarto --version

      - name: Check out repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages:
            any::pak
            github::emitanaka/anicon
            github::hadley/emo
            github::dicook/gretchenalbrecht
            github::mitchelloharawild/icons
            github::heike/vinference
            github::wmurphyrd/fiftystater?ignore
            github::wmurphyrd/colorplaner
            github::rlbarter/superheat
            any::broom
            any::broom.mixed
            any::bslib
            any::colorspace
            any::corrgram
            any::cranlogs
            any::datasauRus
            any::dichromat
            any::dplyr
            any::DT
            any::forecast
            any::gapminder
            any::GGally
            any::gganimate
            any::ggbeeswarm
            any::ggdist
            any::ggmap
            any::ggpcp
            any::ggplot2
            any::ggthemes
            any::glmmTMB
            any::gridExtra
            any::here
            any::htmltools
            any::leaflet
            any::lme4
            any::lubridate
            any::maps
            any::MASS
            any::nullabor
            any::plotly
            any::RColorBrewer
            any::readr
            any::readxl
            any::scales
            any::shiny
            any::splitstackshape
            any::stringr
            any::tidyr
            any::tourr
            any::vinference
            any::viridis
            any::bsicons
            any::thematic

      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GS_AUTH: ${{ secrets.GS_AUTH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
